# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicinereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['symptoms'],
            },
        ),
    ]
